.travis.yml
descwl_shear_testing/tests/test_exists.py
setup.cfg
setup.py

This PR adds a package skeleton and configures the CI.

ENH add skeleton of package and CI testing

---

descwl_shear_testing/render_sim.py
descwl_shear_testing/tests/test_render_sim.py
setup.cfg

This PR has code for rendering sims. It is a copy-paste from an external code base from which I want to use the code, but i'd rather not have a direct dependence.

ENH added code for rendering sims

---

descwl_shear_testing/simple_sim.py
descwl_shear_testing/tests/test_simple_sim.py

This PR adds a test to make sure the PSFs are set.

TST add test to make sure PSFs on simple sims work

---

descwl_shear_testing/simple_sim.py
descwl_shear_testing/tests/test_simple_sim.py

I cherry-picked some commits from the measure branch

Noisefield

---

descwl_shear_sims/simple_sim.py
descwl_shear_sims/tests/test_simple_sim.py

This PR fixes the detection issues with stack.

ENH bigger default buffers

---

.travis.yml
descwl_shear_sims/simple_sim.py
descwl_shear_sims/tests/test_lsst_mask_bits.py

Closes #23 
cc @esheldon 
I am hard coding the flags and double check they match lsst in CI. This lets me dev on the package without having to install it locally.

ENH use the DM stack bit values

---

descwl_shear_sims/gen_masks.py
descwl_shear_sims/lsst_bits.py
descwl_shear_sims/simple_sim.py
descwl_shear_sims/tests/test_gen_masks.py
descwl_shear_sims/tests/test_lsst_mask_bits.py

set the EDGE bit for a border around the image

Turn on edge bits

---

descwl_shear_sims/simple_sim.py

set the default noise to 100

---

descwl_shear_sims/se_obs.py
descwl_shear_sims/simple_sim.py
descwl_shear_sims/tests/test_se_obs.py
descwl_shear_sims/tests/test_simple_sim.py

Psf offsets

---

descwl_shear_sims/simple_sim.py
descwl_shear_sims/tests/test_simple_sim.py

closes #52 
se_dim will be set, only check is that the image size isn't
smaller than 2*edge width
added test

add se_dim keyword

---

descwl_shear_sims/simple_sim.py

closes #36 
This passes the existing tests, but will wait for some code examination and possibly additional tests before merging

set default coadd dims to odd

---

descwl_shear_sims/ps_psf.py
descwl_shear_sims/simple_sim.py
descwl_shear_sims/tests/test_ps_psf.py
descwl_shear_sims/tests/test_simple_sim.py

This PR puts in the fast spatially varying PSF model that was used in the mdet paper.
Closes #46

ENH PS PSF

---

descwl_shear_sims/render_sim.py
descwl_shear_sims/simple_sim.py
descwl_shear_sims/tests/test_simple_sim.py

the cap_radius is sent in arcmin
closes #62

add option to draw ra, dec from sph. cap

---

descwl_shear_sims/simple_sim.py
descwl_shear_sims/tests/test_simple_sim.py

fix bug cacheing band/epoch wcs

---

descwl_shear_sims/gen_star_masks.py
descwl_shear_sims/lsst_bits.py
descwl_shear_sims/render_sim.py
descwl_shear_sims/simple_sim.py
descwl_shear_sims/tests/test_gen_star_masks.py
descwl_shear_sims/tests/test_render_sim.py

Whether or not the star is saturated is stored in the dict
for the object
closes #60

combine sat stars with regular stars

---

descwl_shear_sims/simple_sim.py

use survey.get_flux when rendering fixed star in wldelbend

---

descwl_shear_sims/cache_tools.py
descwl_shear_sims/render_sim.py
descwl_shear_sims/simple_sim.py
descwl_shear_sims/stars.py
descwl_shear_sims/tests/test_render_sim.py
descwl_shear_sims/tests/test_simple_sim.py

closes #73 
closes #74 
It is a bit hard to check we are getting the right mags out for a number of reasons:
1. the zero points are all over the place due to wldeblend
2. we are not rescaling them all on the same system before coadding
3. we are coadding multiple bands

Realistic star mags

---

descwl_shear_sims/simple_sim.py
descwl_shear_sims/stars.py
descwl_shear_sims/tests/test_simple_sim.py

Sample star density

---

descwl_shear_sims/gen_masks.py

make bad columns all width 1

---

descwl_shear_sims/gen_star_masks.py
descwl_shear_sims/lsst_bits.py
descwl_shear_sims/render_sim.py
descwl_shear_sims/saturation.py
descwl_shear_sims/sim_constants.py
descwl_shear_sims/simple_sim.py
descwl_shear_sims/stars.py
descwl_shear_sims/tests/test_gen_star_masks.py
descwl_shear_sims/tests/test_simple_sim.py

closes #82 
Also when not doing saturation, not including the bright stars, but may change this

Saturate images

---

descwl_shear_sims/gen_star_masks.py
descwl_shear_sims/lsst_bits.py
descwl_shear_sims/render_sim.py
descwl_shear_sims/simple_sim.py
descwl_shear_sims/tests/test_render_sim.py

A lot of stuff in here, including a change to the saturation levels that is causing a bias. Those saturation levels were supposed to be improvements based on looking at DC2 like images.
but we should deal with that in a different PR

Bright stars

---

descwl_shear_sims/simple_sim.py
examples/config.yaml

BUG use correct noise for 10-year LSST depth

---

README.md
descwl_shear_sims/galaxy_builder.py
descwl_shear_sims/simple_sim.py
descwl_shear_sims/tests/test_galaxy_builder.py
descwl_shear_sims/tests/test_simple_sim.py
examples/config.yaml

Add option to make wldeblend galaxies round
closes #94

Galaxy builder

---

descwl_shear_sims/cache_tools.py
descwl_shear_sims/gen_sip_wcs.py
descwl_shear_sims/simple_sim.py
descwl_shear_sims/tests/test_gen_sip_wcs.py
descwl_shear_sims/tests/test_simple_sim_wcs.py

closes #48 
TODO
* add code in the sim to use this wcs
* add more than one example wcs
* keep the header around so we can use it to create the wcs in the lsst code
* make descwl_coadds look for that header and use if it it is available

Distort wcs

---

descwl_shear_sims/simple_sim.py
descwl_shear_sims/tests/test_simple_sim.py
descwl_shear_sims/tests/test_simple_sim_psf.py

Add moffat psf without power spectrum

Moffat psf

---

README.md

We can add stuff to this PR to help with the tutorial
I've modified the readme to describe getting the catsim/star mask etc. data

docs for setting up catsim data

---

.github/workflows/test.yml
descwl_shear_sims/sim/galaxy_catalogs.py

don't rotate the catalog, we do this in the Catalog class

---

descwl_shear_sims/__init__.py
descwl_shear_sims/lsst_bits.py
descwl_shear_sims/tests/test_lsst_mask_bits.py

closes #137 
will need to update the COADD code to use this

add new mask plane BRIGHT

---

descwl_shear_sims/psfs/dmpsfs.py
descwl_shear_sims/sim.py
descwl_shear_sims/tests/test_sim.py

Add feature where user can force an exact se_dim (single epoch image dim)
Also add hidden method to DM psfs that gets called

Se dims and hidden method

---

.github/workflows/shear_meas_tests.yml
.github/workflows/test.yml
descwl_shear_sims/sim.py
descwl_shear_sims/tests/test_nonzero_sky.py

new keyword sky_n_sigma adds noise * sky_n_sigma to each image
added a test

add option for nonzero sky

---

descwl_shear_sims/galaxies.py
descwl_shear_sims/shifts.py
descwl_shear_sims/sim.py
descwl_shear_sims/tests/test_pairs.py
shear_meas_tests/test_shear_meas.py

add pair layout and FixedPairGalaxyCatalog

---

CHANGES.md
README.md
descwl_shear_sims/galaxies.py
descwl_shear_sims/shifts.py
descwl_shear_sims/sim.py
descwl_shear_sims/stars.py
descwl_shear_sims/tests/test_sim.py
descwl_shear_sims/version.py
examples/example_ps_psf.py
examples/example_wldeblend.py
examples/example_wldeblend_stars.py
tutorials/tutorial-basic.md

closes #172 
Adjust default buffer to 0, and coadd dims to 250 to match current cell coadd plans.
Also change get_se_dim code to adjust depending if there is dithering or rotation.

Adjust defaults and se dims code

---

CHANGES.md
descwl_shear_sims/sim.py
descwl_shear_sims/tests/test_correlated_noise.py
descwl_shear_sims/tests/test_star_masks_and_bleeds.py

closes #178 
This was added to isolate the effect of star masks from the presence of stars drawn in the image

Option to not draw stars

---

.github/workflows/shear_meas_tests.yml
.github/workflows/test.yml
CHANGES.md
descwl_shear_sims/constants.py
descwl_shear_sims/shifts.py
descwl_shear_sims/stars.py
descwl_shear_sims/tests/test_galaxies.py
descwl_shear_sims/tests/test_sim.py

closes #180 and #181 
This PR adds a randomly rotated hexagonal grid to the code.

ENH add hex layout; fix grid buff

---

descwl_shear_sims/galaxies.py
descwl_shear_sims/layout/layout.py
descwl_shear_sims/shear.py
descwl_shear_sims/sim.py
descwl_shear_sims/tests/test_galaxies.py

change the structure of shear_object so that I can use shear, convergence and deflection angle from halo e.g. see [here](https://github.com/mr-superonion/xlens/blob/86a283f7339c3ed08468fc50f57ab621ff44e28b/xlens/simulation/simulator/halo.py#L8).

Slightly Change the structure of Shear Object 

---

descwl_shear_sims/sim.py

Corresponding [issue](https://github.com/LSSTDESC/descwl-shear-sims/issues/192)

return dict of list of se_wcs

---

descwl_shear_sims/sim.py

`make_exp` returns ra, dec, and redshift of simulated objects. As mentioned in this [issue](https://github.com/LSSTDESC/descwl-shear-sims/issues/129).

Return "truth catalog" info

---

.github/workflows/shear_meas_tests.yml

try to fix mamba seg fault
